POST /graphql HTTP/1.1
Host: localhost:5069
Content-Type: application/json
Content-Length: 234

{
  "query": "{\n  contactItems {\n    totalCount\n    nodes {\n      createdAt\n      description\n      href\n      icon\n      id\n      internalId\n      key\n      title\n      updatedAt\n      version\n    }\n  }\n}",
  "variables": {}
}