POST /graphql HTTP/1.1
Host: localhost:5069
Content-Type: application/json
Content-Length: 350

{"query":"{\n  customers {\n    totalCount\n    items {\n      createdAt\n      href\n      id\n      title\n      updatedAt\n      version\n      portfolioCategories {\n        totalCount\n      }\n      portfolioItems {\n        totalCount\n      }\n      portfolioTechnologyCategories {\n        totalCount\n      }\n    }\n  }\n}","variables":{}}