POST /graphql HTTP/1.1
Host: localhost:5069
Content-Type: application/json
Content-Length: 482

{"query":"{\n  educationItems {\n    totalCount\n    nodes {\n      categoryId\n      createdAt\n      description\n      href\n      id\n      internalId\n      location\n      subjects\n      title\n      updatedAt\n      version\n      category {\n        associatedCategoryTypes\n        createdAt\n        id\n        internalId\n        title\n        updatedAt\n        version\n      }\n      timePeriod {\n        end\n        start\n      }\n    }\n  }\n}","variables":{}}