POST /graphql HTTP/1.1
Host: localhost:5069
Content-Type: application/json
Content-Length: 207

{"query":"{\n  health {\n    status\n    totalDuration\n    entries {\n      key\n      value {\n        description\n        duration\n        status\n        tags\n      }\n    }\n  }\n}\n","variables":{}}