POST /graphql HTTP/1.1
Host: localhost:5069
Content-Type: application/json
Content-Length: 215

{
  "query": "{\n  languageById(id: \"TGFuZ3VhZ2UKZzM5MjYwNmNhZWZjZjQzNmJiMGQ5YWI1ZDU5MGVkMjA0\") {\n    createdAt\n    id\n    internalId\n    proficiency\n    title\n    updatedAt\n    version\n  }\n}",
  "variables": {}
}