POST /graphql HTTP/1.1
Host: localhost:5069
Content-Type: application/json
Content-Length: 622

{"query":"{\n  technologyCategories {\n    totalCount\n    items {\n      createdAt\n      href\n      id\n      title\n      updatedAt\n      version\n      ... on InformationTechnologyCategory {\n        createdAt\n        href\n        id\n        title\n        updatedAt\n        version\n      }\n      ... on SoftwareDevelopmentCategory {\n        createdAt\n        href\n        id\n        title\n        updatedAt\n        version\n      }\n      ... on TechnologyCategory {\n        createdAt\n        href\n        id\n        title\n        updatedAt\n        version\n      }\n    }\n  }\n}","variables":{}}