POST /graphql HTTP/1.1
Host: localhost:5069
Content-Type: application/json
Content-Length: 185

{"query":"{\n  textItems {\n    totalCount\n    items {\n      content\n      createdAt\n      id\n      key\n      title\n      updatedAt\n      version\n    }\n  }\n}","variables":{}}