global using Humanizer;
global using Microsoft.Extensions.Options;
global using OneOf;
global using System.ComponentModel.DataAnnotations;
global using System.Diagnostics.CodeAnalysis;
global using ui.Consts;
global using ui.Enums;
global using ui.Interfaces;
global using ui.Models;
