namespace ui.Enums;

public enum EmailErrorCodeType
{
    NONE,
    FAILED_TO_SEND,
    REQUIRED,
    INVALID_EMAIL_ADDRESS,
    EMPTY_CONTENT,
    UNUSABLE_CONTENT,
    MARKUP_IS_NOT_ALLOWED,
    HTML_ATTRIBUTES_ARE_NOT_ALLOWED,
    SCRIPT_TAGS_ARE_NOT_ALLOWED,
    STYLE_TAGS_ARE_NOT_ALLOWED,
    LINK_TAGS_ARE_NOT_ALLOWED,
    META_TAGS_ARE_NOT_ALLOWED
}
